services:
  - type: web
    name: amos-watches
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips '*'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
